name: Java Tester

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 18
      uses: oracle-actions/setup-java@v1
      with:
        version: '18.0.2.1'
        release: 18
